[package]
name = "vati"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-i18n = "3"
services = { path = "../services" }
service-locator = "0.2.0"
